const mockNotes = [
  // {
  //   id: "1",
  //   title: "Grocery List",
  //   isFavorite: true,
  //   isDeleted: false,
  //   content: "Milk, eggs, bread, cheese",
  // },
  // {
  //   id: "2",
  //   title: "Meeting Notes",
  //   isFavorite: false,
  //   isDeleted: false,
  //   content: "Discuss project timeline, assign tasks",
  // },
  // {
  //   id: "3",
  //   title: "Ideas for Blog Post",
  //   isFavorite: true,
  //   isDeleted: false,
  //   content: "Topic: Productivity tips, Target audience: Students",
  // },
  // {
  //   id: "4",
  //   title: "Book Recommendations",
  //   isFavorite: false,
  //   isDeleted: false,
  //   content: "Sapiens, The Lean Startup, Atomic Habits",
  // },
  // {
  //   id: "5",
  //   title: "Workout Routine",
  //   isFavorite: true,
  //   isDeleted: false,
  //   content: "Monday: Chest and Triceps, Tuesday: Back and Biceps",
  // },
  // {
  //   id: "6",
  //   title: "Travel Plans",
  //   isFavorite: false,
  //   isDeleted: false,
  //   content: "Destination: Paris, Dates: July 10-17",
  // },
  // {
  //   id: "7",
  //   title: "Recipes to Try",
  //   isFavorite: true,
  //   isDeleted: false,
  //   content: "Pasta Carbonara, Chicken Stir-fry, Chocolate Cake",
  // },
  // {
  //   id: "8",
  //   title: "Gift Ideas",
  //   isFavorite: false,
  //   isDeleted: false,
  //   content: "Birthday: John - Watch, Anniversary: Sarah - Necklace",
  // },
  // {
  //   id: "9",
  //   title: "Home Improvement Projects",
  //   isFavorite: true,
  //   isDeleted: false,
  //   content: "Paint living room, Replace kitchen faucet",
  // },
  // {
  //   id: "10",
  //   title: "Financial Goals",
  //   isFavorite: false,
  //   isDeleted: false,
  //   content: "Save for down payment, Invest in stocks",
  // },
  // {
  //   id: "11",
  //   title: "Learning Resources",
  //   isFavorite: true,
  //   isDeleted: false,
  //   content: "Online courses, Books, Podcasts",
  // },
  // {
  //   id: "12",
  //   title: "Personal Development",
  //   isFavorite: false,
  //   isDeleted: false,
  //   content: "Meditation, Journaling, Exercise",
  // },
  // {
  //   id: "13",
  //   title: "Side Hustle Ideas",
  //   isFavorite: true,
  //   isDeleted: false,
  //   content: "Freelance writing, Online tutoring, Graphic design",
  // },
  // {
  //   id: "14",
  //   title: "Networking Events",
  //   isFavorite: false,
  //   isDeleted: false,
  //   content: "Industry conference, Local meetup",
  // },
  // {
  //   id: "15",
  //   title: "Volunteer Opportunities",
  //   isFavorite: true,
  //   isDeleted: false,
  //   content: "Animal shelter, Food bank, Community garden",
  // },
  // {
  //   id: "16",
  //   title: "Daily Affirmations",
  //   isFavorite: false,
  //   isDeleted: false,
  //   content: "I am confident, I am capable, I am worthy",
  // },
  // {
  //   id: "17",
  //   title: "Gratitude List",
  //   isFavorite: true,
  //   isDeleted: false,
  //   content: "Family, Friends, Health",
  // },
  // {
  //   id: "18",
  //   title: "Long-Term Goals",
  //   isFavorite: false,
  //   isDeleted: false,
  //   content: "Career advancement, Financial independence",
  // },
  // {
  //   id: "19",
  //   title: "Project A - Brainstorming",
  //   isFavorite: true,
  //   isDeleted: false,
  //   content: "Initial ideas and concepts for Project A.",
  // },
  {
    id: "20",
    title: "Client Meeting - Recap",
    isFavorite: false,
    isDeleted: false,
    content: "Summary of key decisions made during the client meeting.",
  },
  {
    id: "21",
    title: "Marketing Campaign Ideas",
    isFavorite: true,
    isDeleted: false,
    content: "New strategies for the upcoming marketing campaign.",
  },
  {
    id: "22",
    title: "Team Building Activities",
    isFavorite: false,
    isDeleted: false,
    content: "Suggestions for improving team collaboration and morale.",
  },
  {
    id: "23",
    title: "Website Redesign - Feedback",
    isFavorite: true,
    isDeleted: false,
    content: "Collected feedback on the proposed website redesign.",
  },
  {
    id: "24",
    title: "Competitor Analysis",
    isFavorite: false,
    isDeleted: false,
    content: "Analysis of competitor strategies and market positioning.",
  },
  {
    id: "25",
    title: "New Software Evaluation",
    isFavorite: true,
    isDeleted: false,
    content: "Evaluation of potential new software solutions for the company.",
  },
  {
    id: "26",
    title: "Employee Training Program",
    isFavorite: false,
    isDeleted: false,
    content: "Outline for the upcoming employee training program.",
  },
  {
    id: "27",
    title: "Customer Survey Results",
    isFavorite: true,
    isDeleted: false,
    content: "Summary of key findings from the recent customer survey.",
  },
  {
    id: "28",
    title: "Budget Planning - Q3",
    isFavorite: false,
    isDeleted: false,
    content: "Preliminary budget plan for the third quarter.",
  },
  {
    id: "29",
    title: "Social Media Strategy",
    isFavorite: true,
    isDeleted: false,
    content: "Plan for enhancing the company's social media presence.",
  },
  {
    id: "30",
    title: "Year-End Review",
    isFavorite: false,
    isDeleted: false,
    content: "Summary of key achievements and challenges from the past year.",
  },
];

export default mockNotes;
